services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=ny_taxi
      - POSTGRES_PASSWORD=root
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - pg-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    networks:
      - pg-network
volumes:
    ny_taxi_postgres_data:
    pgadmin_data:
networks:
  pg-network:
    name: pg-network
